package controller

// Vendored from github.com/google/uuid v1.6.0 hash.go (BSD-3-Clause,
// Copyright 2016 Google Inc., see that module's LICENSE). Only NewSHA1's
// path is taken; local diffs are marked.

import (
	"crypto/sha1"
	"hash"
	"uuid"
)

// newHashUUID returns a new UUID derived from the hash of space concatenated
// with data generated by h. The hash should be at least 16 byte in length.
// The first 16 bytes of the hash are used to form the UUID. The version of
// the UUID will be the lower 4 bits of version.
func newHashUUID(h hash.Hash, space uuid.UUID, data []byte, version int) uuid.UUID { // local diff: std uuid type, unexported
	h.Reset()
	h.Write(space[:]) //nolint:errcheck
	h.Write(data)     //nolint:errcheck
	s := h.Sum(nil)
	var u uuid.UUID // local diff: named u, not uuid -- the std package holds that name here
	copy(u[:], s)
	u[6] = (u[6] & 0x0f) | uint8((version&0xf)<<4)
	u[8] = (u[8] & 0x3f) | 0x80 // RFC 4122 variant
	return u
}

// newSHA1UUID returns a new SHA1 (Version 5) UUID based on the
// supplied name space and data.
func newSHA1UUID(space uuid.UUID, data []byte) uuid.UUID {
	return newHashUUID(sha1.New(), space, data, 5)
}
