-- The claim does `ORDER BY id`, so the planner scans by the PRIMARY KEY and
-- filters status inline. As done/dead rows accumulate at low ids, every claim
-- scans straight through that graveyard to reach live rows (measured: a single
-- claim went 0.057ms -> 41.8ms at 150k done rows, a ~730x regression).
--
-- idx_claim_ready / idx_claim_processing (004) are keyed on can_run_after /
-- lease_until and cannot satisfy an `id` ordering across the
-- `ready OR expired-processing` predicate, so this query never uses them.
--
-- This partial index is keyed on `id` and covers BOTH live states, giving the
-- ordered scan a graveyard-free path while preserving FIFO id ordering. After
-- this, the same claim stays ~0.09ms regardless of how many done rows pile up.
CREATE INDEX IF NOT EXISTS idx_claim_active ON message_log (id) WHERE status IN ('ready', 'processing');
