<script lang="ts">
	import { onMount } from 'svelte';
	import SearchResult from '../search-result/search-result.svelte';
	import { SearchState } from './board-search-state.svelte';

	const state = new SearchState();

	function submit(event: SubmitEvent): void {
		event.preventDefault();
		const query = state.query.trim();
		if (query === '') {
			return;
		}

		const url = new URL(window.location.href);
		url.searchParams.set('q', query);
		window.history.replaceState(null, '', url);
		void state.search();
	}

	// a shared /search/?q= link runs its query on arrival; one-time init,
	// deliberately not an $effect -- search() reads state.query, so a
	// tracked scope would re-run on every keystroke and revert the input
	onMount(() => {
		const query = new URLSearchParams(window.location.search).get('q');
		if (query !== null && query !== '') {
			state.query = query;
			void state.search();
		}
	});
</script>

<div class="board-search">
	<form class="search-form" onsubmit={submit}>
		<input
			type="search"
			placeholder="a VK code, a log line, or any phrase from a thread"
			aria-label="Search the board"
			bind:value={state.query}
		/>
		<button type="submit" class="era-button">Search</button>
	</form>
	{#if state.phase === 'searching'}
		<p class="search-status">searching…</p>
	{:else if state.phase === 'unavailable'}
		<p class="search-status">the search index is missing — it is generated by the site build</p>
	{:else if state.phase === 'stopped'}
		<p class="search-status">the search could not finish — run it again</p>
	{:else if state.phase === 'done'}
		{#if state.totalCount === 0}
			<p class="search-status">no threads match</p>
		{:else if state.hits.length < state.totalCount}
			<p class="search-status">
				{state.totalCount} threads match — showing the first {state.hits.length}
			</p>
		{:else}
			<p class="search-status">
				{state.totalCount}
				{state.totalCount === 1 ? 'thread matches' : 'threads match'}
			</p>
		{/if}
		<div class="search-results">
			{#each state.hits as hit (hit.href)}
				<SearchResult title={hit.title} href={hit.href} excerpt={hit.excerpt} />
			{/each}
		</div>
	{/if}
</div>

<style src="./board-search.css"></style>
