package main

// idempotency-key lab: does AppendMessage's retry-safety claim gate
// (idempotency_key) actually prevent a double-publish, and does its
// cleanup (SweepExpiredIdempotencyKeys, Topic.IdempotencyKeyTTL) actually
// drain it the way compactionheadretentionlab proves for compaction?
//
// Five scenarios:
//   - duplicateKeyScenario: the SAME idempotency key across repeated
//     Produce calls must land exactly one message_log row -- this is what
//     makes it safe for DBRetry.Wrap to retry AppendMessage's whole
//     producerFunc-and-insert after an ambiguous commit instead of
//     double-publishing.
//   - distinctKeysScenario: different keys must never collide -- the gate
//     shouldn't block legitimate, distinct publishes.
//   - autoGeneratedKeyScenario: leaving ProduceOptions.IdempotencyKey unset
//     mints a fresh key per call, so repeated Produce calls with no
//     explicit key are NOT mistaken for retries of one another.
//   - sweepScenario: idempotency_key rows older than IdempotencyKeyTTL get
//     swept by the janitor in bounded batches; a key inside the TTL window
//     survives -- same shape as compactionheadretentionlab proves for
//     compaction_head.
//   - configRoundTripScenario: IdempotencyKeyTTL persists correctly through
//     re-registration -- Topic-level config, not a per-call default that
//     silently resets. A re-register with a changed mutable config field replaces the
//     stored value; only a changed PartitionSize is rejected.

import (
	"context"
	"errors"
	"fmt"
	"os"
	"time"

	"github.com/agentstax/vulkan/examples/phase_1/common"
	"github.com/agentstax/vulkan/pkg/admin"
	coredatastore "github.com/agentstax/vulkan/pkg/datastore"
	"github.com/agentstax/vulkan/pkg/producer"
	"github.com/agentstax/vulkan/pkg/topic"
	topiccontroller "github.com/agentstax/vulkan/pkg/topic/controller"
	janitordatastore "github.com/agentstax/vulkan/pkg/worker/janitor/datastore"
	"github.com/google/uuid"
)

func main() {
	ctx := context.Background()

	ds, err := coredatastore.NewPostgresDatastore(ctx, &coredatastore.PostgresConnectionConfig{
		User: "example_user", Pass: "example_password",
		Host: "localhost", Port: 5432, Database: "example_db",
	})
	must(err)
	defer ds.Close()

	duplicateKeyScenario(ctx, ds)
	distinctKeysScenario(ctx, ds)
	autoGeneratedKeyScenario(ctx, ds)
	sweepScenario(ctx, ds)
	configRoundTripScenario(ctx, ds)

	fmt.Println("\n✅ IDEMPOTENCY KEYS LAB PASSED")
	fmt.Println("   a retried AppendMessage under the same key lands exactly once, distinct")
	fmt.Println("   keys never collide, an unset key protects only within one call, the sweep")
	fmt.Println("   drains expired claims without touching live ones, and IdempotencyKeyTTL")
	fmt.Println("   survives a topic re-registration unchanged.")
}

func duplicateKeyScenario(ctx context.Context, ds *coredatastore.PostgresDatastore) {
	step("duplicate key: retrying AppendMessage under the same key must not double-publish")

	mAdmin, err := admin.NewMessageAdmin(ds, &admin.MessageAdminConfig{AllowDestroy: true})
	must(err)
	must(mAdmin.RegisterSystem(ctx, nil))

	topicName := fmt.Sprintf("phase9.idempotencykeyslab.duplicate.%d", time.Now().UnixNano())
	tp, err := mAdmin.RegisterTopic(ctx, topicName, topic.SchemaVersion(1), &topiccontroller.TopicConfig{PartitionSize: 1000})
	must(err)
	defer func() {
		must(mAdmin.DestroyTopic(ctx, topicName, topic.SchemaVersion(1), admin.DestroyOptions{Force: true}))
	}()

	wp, err := producer.NewProducer[common.Work](ds, nil)
	must(err)
	wpInstance, err := wp.Register(ctx, tp.Name, topic.SchemaVersion(1))
	must(err)

	key, err := uuid.NewV7()
	must(err)
	opts := producer.ProduceOptions{IdempotencyKey: key}

	calls := 0
	fn := func(ctx context.Context, tx producer.Tx, gotKey uuid.UUID) (*common.Work, error) {
		calls++
		if gotKey != key {
			die("producerFunc did not receive the idempotency key it was given")
		}
		return common.NewWork(30, "admin@example.com")
	}

	// three "retries" under the exact same key -- what DBRetry.Wrap would do
	// after an ambiguous commit
	for attempt := range 3 {
		produced, err := wpInstance.ProduceFunc(ctx, fn, opts)
		must(err)
		if attempt == 0 && (produced.Duplicate || produced.Id == 0) {
			die(fmt.Sprintf("first call must not report Duplicate and must carry a stored id, got Duplicate=%t Id=%d", produced.Duplicate, produced.Id))
		}
		if attempt > 0 && (!produced.Duplicate || produced.Id != 0) {
			die(fmt.Sprintf("retried call under the same key must report Duplicate=true Id=0, got Duplicate=%t Id=%d", produced.Duplicate, produced.Id))
		}
	}

	assertMessageLogCount(ctx, ds, tp.Id, 1)
	if calls != 3 {
		die(fmt.Sprintf("producerFunc ran %d times, want 3 -- re-running it is the documented contract", calls))
	}
	fmt.Printf("  ✓ producerFunc ran 3 times (documented contract), message_log has exactly 1 row,\n")
	fmt.Printf("    first call stored the row, both retries reported Duplicate\n")
}

func distinctKeysScenario(ctx context.Context, ds *coredatastore.PostgresDatastore) {
	step("distinct keys: the claim gate must never block a legitimately different publish")

	mAdmin, err := admin.NewMessageAdmin(ds, &admin.MessageAdminConfig{AllowDestroy: true})
	must(err)

	topicName := fmt.Sprintf("phase9.idempotencykeyslab.distinct.%d", time.Now().UnixNano())
	tp, err := mAdmin.RegisterTopic(ctx, topicName, topic.SchemaVersion(1), &topiccontroller.TopicConfig{PartitionSize: 1000})
	must(err)
	defer func() {
		must(mAdmin.DestroyTopic(ctx, topicName, topic.SchemaVersion(1), admin.DestroyOptions{Force: true}))
	}()

	wp, err := producer.NewProducer[common.Work](ds, nil)
	must(err)
	wpInstance, err := wp.Register(ctx, tp.Name, topic.SchemaVersion(1))
	must(err)

	for range 5 {
		key, err := uuid.NewV7()
		must(err)
		_, err = wpInstance.ProduceFunc(ctx, func(ctx context.Context, tx producer.Tx, _ uuid.UUID) (*common.Work, error) {
			return common.NewWork(30, "admin@example.com")
		}, producer.ProduceOptions{IdempotencyKey: key})
		must(err)
	}

	assertMessageLogCount(ctx, ds, tp.Id, 5)
	fmt.Println("  ✓ 5 distinct keys -> 5 distinct rows")
}

func autoGeneratedKeyScenario(ctx context.Context, ds *coredatastore.PostgresDatastore) {
	step("auto-generated key: an unset IdempotencyKey protects only within one call")

	mAdmin, err := admin.NewMessageAdmin(ds, &admin.MessageAdminConfig{AllowDestroy: true})
	must(err)

	topicName := fmt.Sprintf("phase9.idempotencykeyslab.auto.%d", time.Now().UnixNano())
	tp, err := mAdmin.RegisterTopic(ctx, topicName, topic.SchemaVersion(1), &topiccontroller.TopicConfig{PartitionSize: 1000})
	must(err)
	defer func() {
		must(mAdmin.DestroyTopic(ctx, topicName, topic.SchemaVersion(1), admin.DestroyOptions{Force: true}))
	}()

	wp, err := producer.NewProducer[common.Work](ds, nil)
	must(err)
	wpInstance, err := wp.Register(ctx, tp.Name, topic.SchemaVersion(1))
	must(err)

	// three SEPARATE calls, no explicit key -- these are not retries of one
	// another and must NOT collapse into one row
	for range 3 {
		_, err := wpInstance.ProduceFunc(ctx, func(ctx context.Context, tx producer.Tx, k uuid.UUID) (*common.Work, error) {
			if k == uuid.Nil {
				die("AppendMessage did not resolve a fresh key for an unset ProduceOptions.IdempotencyKey")
			}
			return common.NewWork(30, "admin@example.com")
		}, producer.ProduceOptions{})
		must(err)
	}

	assertMessageLogCount(ctx, ds, tp.Id, 3)
	fmt.Println("  ✓ 3 separate calls with no explicit key -> 3 distinct rows, not deduped against each other")
}

func sweepScenario(ctx context.Context, ds *coredatastore.PostgresDatastore) {
	step("sweep: expired idempotency_key rows are drained, live ones survive")

	const ttl = 100 * time.Millisecond
	const batchSize = 2 // small on purpose -- forces the sweep to loop across multiple batches

	mAdmin, err := admin.NewMessageAdmin(ds, &admin.MessageAdminConfig{AllowDestroy: true})
	must(err)

	topicName := fmt.Sprintf("phase9.idempotencykeyslab.sweep.%d", time.Now().UnixNano())
	tp, err := mAdmin.RegisterTopic(ctx, topicName, topic.SchemaVersion(1), &topiccontroller.TopicConfig{PartitionSize: 1000})
	must(err)
	defer func() {
		must(mAdmin.DestroyTopic(ctx, topicName, topic.SchemaVersion(1), admin.DestroyOptions{Force: true}))
	}()

	wp, err := producer.NewProducer[common.Work](ds, nil)
	must(err)
	wpInstance, err := wp.Register(ctx, tp.Name, topic.SchemaVersion(1))
	must(err)
	janitorDatastore, err := janitordatastore.NewJanitorDatastore(ds, nil)
	must(err)

	fn := func(ctx context.Context, tx producer.Tx, _ uuid.UUID) (*common.Work, error) {
		return common.NewWork(30, "admin@example.com")
	}

	// 5 dormant claims -- batchSize=2 means this drains across 3 batches
	for range 5 {
		_, err := wpInstance.ProduceFunc(ctx, fn, producer.ProduceOptions{})
		must(err)
	}
	assertIdempotencyKeysCount(ctx, ds, tp.Id, 5)

	// backdate them all past ttl
	_, err = ds.Pool.Exec(ctx, fmt.Sprintf(`UPDATE idempotency_key_%d SET created_at = now() - interval '1 hour';`, tp.Id))
	must(err)

	// one alive claim, published after the backdate, well inside ttl
	_, err = wpInstance.ProduceFunc(ctx, fn, producer.ProduceOptions{})
	must(err)
	assertIdempotencyKeysCount(ctx, ds, tp.Id, 6)

	must(janitorDatastore.SweepExpiredIdempotencyKeys(ctx, tp.Id, ttl, batchSize))

	assertIdempotencyKeysCount(ctx, ds, tp.Id, 1)
	fmt.Println("  ✓ 5 dormant claims swept across multiple batches, the 1 live claim survives")
}

func configRoundTripScenario(ctx context.Context, ds *coredatastore.PostgresDatastore) {
	step("config round trip: IdempotencyKeyTTL persists correctly through re-registration")

	mAdmin, err := admin.NewMessageAdmin(ds, &admin.MessageAdminConfig{AllowDestroy: true})
	must(err)

	topicName := fmt.Sprintf("phase9.idempotencykeyslab.roundtrip.%d", time.Now().UnixNano())
	defer func() {
		must(mAdmin.DestroyTopic(ctx, topicName, topic.SchemaVersion(1), admin.DestroyOptions{Force: true}))
	}()

	tp1, err := mAdmin.RegisterTopic(ctx, topicName, topic.SchemaVersion(1), &topiccontroller.TopicConfig{PartitionSize: 1000})
	must(err)
	if tp1.IdempotencyKeyTTL != time.Hour {
		die(fmt.Sprintf("default IdempotencyKeyTTL = %v, want 1h", tp1.IdempotencyKeyTTL))
	}

	// a re-register with the same (defaulted) config leaves the row alone
	tp2, err := mAdmin.RegisterTopic(ctx, topicName, topic.SchemaVersion(1), &topiccontroller.TopicConfig{PartitionSize: 1000})
	must(err)
	if tp2.IdempotencyKeyTTL != time.Hour {
		die(fmt.Sprintf("re-registered IdempotencyKeyTTL = %v, want 1h", tp2.IdempotencyKeyTTL))
	}
	fmt.Println("  ✓ default IdempotencyKeyTTL (1h) survives a re-register unchanged")

	// the newest declaration wins -- a changed mutable config field replaces the stored one
	tp3, err := mAdmin.RegisterTopic(ctx, topicName, topic.SchemaVersion(1), &topiccontroller.TopicConfig{PartitionSize: 1000, IdempotencyKeyTTL: 2 * time.Hour})
	must(err)
	if tp3.IdempotencyKeyTTL != 2*time.Hour {
		die(fmt.Sprintf("re-declared IdempotencyKeyTTL = %v, want 2h", tp3.IdempotencyKeyTTL))
	}
	fmt.Println("  ✓ a changed IdempotencyKeyTTL on re-register replaces the stored value")

	// partition_size is not mutable config -- message_log's boundaries depend on it
	_, err = mAdmin.RegisterTopic(ctx, topicName, topic.SchemaVersion(1), &topiccontroller.TopicConfig{PartitionSize: 2000, IdempotencyKeyTTL: 2 * time.Hour})
	if !errors.Is(err, topic.ErrTopicConfigMismatch) {
		die(fmt.Sprintf("expected ErrTopicConfigMismatch for a changed PartitionSize, got %v", err))
	}
	fmt.Println("  ✓ a changed PartitionSize on re-register is rejected")
}

// ---- helpers ----

func assertMessageLogCount(ctx context.Context, ds *coredatastore.PostgresDatastore, topicId int64, want int) {
	var count int
	must(ds.Pool.QueryRow(ctx, fmt.Sprintf(`SELECT COUNT(*) FROM message_log_%d;`, topicId)).Scan(&count))
	if count != want {
		die(fmt.Sprintf("message_log_%d has %d rows, want %d", topicId, count, want))
	}
}

func assertIdempotencyKeysCount(ctx context.Context, ds *coredatastore.PostgresDatastore, topicId int64, want int) {
	var count int
	must(ds.Pool.QueryRow(ctx, fmt.Sprintf(`SELECT COUNT(*) FROM idempotency_key_%d;`, topicId)).Scan(&count))
	if count != want {
		die(fmt.Sprintf("idempotency_key_%d has %d rows, want %d", topicId, count, want))
	}
}

func step(s string) { fmt.Printf("\n--- %s ---\n", s) }
func must(err error) {
	if err != nil {
		die(err.Error())
	}
}
func die(msg string) {
	fmt.Printf("\n❌ LAB FAILED: %s\n", msg)
	os.Exit(1)
}
