package main

// idempotency-key lab: does AppendMessage's retry-safety claim gate
// (idempotency_key) actually prevent a double-publish, and does its
// cleanup (SweepExpiredIdempotencyKeys, Topic.IdempotencyKeyTTL) actually
// drain it the way latestkeysretentionlab proves for compaction?
//
// Six scenarios:
//   - duplicateKeyScenario: the SAME idempotency key across repeated
//     Produce calls must land exactly one message_log row -- this is what
//     makes it safe for DBRetry.Wrap to retry AppendMessage's whole
//     producerFunc-and-insert after an ambiguous commit instead of
//     double-publishing.
//   - distinctKeysScenario: different keys must never collide -- the gate
//     shouldn't block legitimate, distinct publishes.
//   - autoGeneratedKeyScenario: leaving ProduceOptions.IdempotencyKey unset
//     mints a fresh key per call, so repeated Produce calls with no
//     explicit key are NOT mistaken for retries of one another.
//   - sweepScenario: idempotency_key rows older than IdempotencyKeyTTL get
//     swept by the janitor in bounded batches; a key inside the TTL window
//     survives -- same shape as latestkeysretentionlab proves for
//     latest_key.
//   - configRoundTripScenario: IdempotencyKeyTTL persists correctly through
//     re-registration -- Topic-level config, not a per-call default that
//     silently resets and trips ErrTopicConfigMismatch.
//   - skipIdempotencyScenario: ProduceOptions.SkipIdempotency opts a single
//     call out of the claim gate entirely -- zero idempotency_key rows
//     written, IdempotencyKey ignored, and (the honest cost of the tradeoff)
//     repeated calls under the same key genuinely double-publish. A
//     protected call in the same topic right after is unaffected -- the
//     opt-out is per-call, not a topic-wide switch.

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/agentstax/vulkan/examples/phase_1/common"
	"github.com/agentstax/vulkan/pkg/consumer"
	coredatastore "github.com/agentstax/vulkan/pkg/datastore"
	"github.com/agentstax/vulkan/pkg/producer"
	"github.com/agentstax/vulkan/pkg/topic"
	"github.com/google/uuid"
)

func main() {
	ctx := context.Background()

	ds, err := coredatastore.NewPostgresDatastore(ctx, &coredatastore.PostgresConnectionConfig{
		User: "example_user", Pass: "example_password",
		Host: "localhost", Port: 5432, Database: "example_db",
	})
	must(err)

	duplicateKeyScenario(ctx, ds)
	distinctKeysScenario(ctx, ds)
	autoGeneratedKeyScenario(ctx, ds)
	sweepScenario(ctx, ds)
	configRoundTripScenario(ctx, ds)
	skipIdempotencyScenario(ctx, ds)

	fmt.Println("\n✅ IDEMPOTENCY KEYS LAB PASSED")
	fmt.Println("   a retried AppendMessage under the same key lands exactly once, distinct")
	fmt.Println("   keys never collide, an unset key protects only within one call, the sweep")
	fmt.Println("   drains expired claims without touching live ones, IdempotencyKeyTTL")
	fmt.Println("   survives a topic re-registration unchanged, and SkipIdempotency opts a")
	fmt.Println("   single call out of the claim gate without affecting the rest of the topic.")
}

func duplicateKeyScenario(ctx context.Context, ds *coredatastore.PostgresDatastore) {
	step("duplicate key: retrying AppendMessage under the same key must not double-publish")

	topicName := fmt.Sprintf("phase9.idempotencykeyslab.duplicate.%d", time.Now().UnixNano())
	tp, err := topic.Register(ctx, ds, topic.Config{Name: topicName, PartitionSize: 1000})
	must(err)
	defer func() { must(topic.Destroy(ctx, ds, topicName)) }()

	pd := producer.NewProducerDatastore[common.Work](ds, nil)
	wp := producer.NewMessageProducer(tp, pd)

	key, err := uuid.NewV7()
	must(err)
	opts := producer.ProduceOptions{IdempotencyKey: key}

	calls := 0
	fn := func(ctx context.Context, tx producer.Tx, gotKey uuid.UUID) (*common.Work, error) {
		calls++
		if gotKey != key {
			die("producerFunc did not receive the idempotency key it was given")
		}
		return common.NewWork(30, "admin@example.com")
	}

	// three "retries" under the exact same key -- what DBRetry.Wrap would do
	// after an ambiguous commit
	for range 3 {
		_, err := wp.Produce(ctx, fn, opts)
		must(err)
	}

	assertMessageLogCount(ctx, ds, tp.Id, 1)
	if calls != 3 {
		die(fmt.Sprintf("producerFunc ran %d times, want 3 -- re-running it is the documented contract", calls))
	}
	fmt.Printf("  ✓ producerFunc ran 3 times (documented contract) but message_log has exactly 1 row\n")
}

func distinctKeysScenario(ctx context.Context, ds *coredatastore.PostgresDatastore) {
	step("distinct keys: the claim gate must never block a legitimately different publish")

	topicName := fmt.Sprintf("phase9.idempotencykeyslab.distinct.%d", time.Now().UnixNano())
	tp, err := topic.Register(ctx, ds, topic.Config{Name: topicName, PartitionSize: 1000})
	must(err)
	defer func() { must(topic.Destroy(ctx, ds, topicName)) }()

	pd := producer.NewProducerDatastore[common.Work](ds, nil)
	wp := producer.NewMessageProducer(tp, pd)

	for range 5 {
		key, err := uuid.NewV7()
		must(err)
		_, err = wp.Produce(ctx, func(ctx context.Context, tx producer.Tx, _ uuid.UUID) (*common.Work, error) {
			return common.NewWork(30, "admin@example.com")
		}, producer.ProduceOptions{IdempotencyKey: key})
		must(err)
	}

	assertMessageLogCount(ctx, ds, tp.Id, 5)
	fmt.Println("  ✓ 5 distinct keys -> 5 distinct rows")
}

func autoGeneratedKeyScenario(ctx context.Context, ds *coredatastore.PostgresDatastore) {
	step("auto-generated key: an unset IdempotencyKey protects only within one call")

	topicName := fmt.Sprintf("phase9.idempotencykeyslab.auto.%d", time.Now().UnixNano())
	tp, err := topic.Register(ctx, ds, topic.Config{Name: topicName, PartitionSize: 1000})
	must(err)
	defer func() { must(topic.Destroy(ctx, ds, topicName)) }()

	pd := producer.NewProducerDatastore[common.Work](ds, nil)
	wp := producer.NewMessageProducer(tp, pd)

	// three SEPARATE calls, no explicit key -- these are not retries of one
	// another and must NOT collapse into one row
	for range 3 {
		_, err := wp.Produce(ctx, func(ctx context.Context, tx producer.Tx, k uuid.UUID) (*common.Work, error) {
			if k == uuid.Nil {
				die("AppendMessage did not resolve a fresh key for an unset ProduceOptions.IdempotencyKey")
			}
			return common.NewWork(30, "admin@example.com")
		}, producer.ProduceOptions{})
		must(err)
	}

	assertMessageLogCount(ctx, ds, tp.Id, 3)
	fmt.Println("  ✓ 3 separate calls with no explicit key -> 3 distinct rows, not deduped against each other")
}

func sweepScenario(ctx context.Context, ds *coredatastore.PostgresDatastore) {
	step("sweep: expired idempotency_key rows are drained, live ones survive")

	const ttl = 100 * time.Millisecond
	const batchSize = 2 // small on purpose -- forces the sweep to loop across multiple batches

	topicName := fmt.Sprintf("phase9.idempotencykeyslab.sweep.%d", time.Now().UnixNano())
	tp, err := topic.Register(ctx, ds, topic.Config{Name: topicName, PartitionSize: 1000})
	must(err)
	defer func() { must(topic.Destroy(ctx, ds, topicName)) }()

	pd := producer.NewProducerDatastore[common.Work](ds, nil)
	wp := producer.NewMessageProducer(tp, pd)
	cd := consumer.NewConsumerDatastore[common.Work](ds, nil)

	fn := func(ctx context.Context, tx producer.Tx, _ uuid.UUID) (*common.Work, error) {
		return common.NewWork(30, "admin@example.com")
	}

	// 5 dormant claims -- batchSize=2 means this drains across 3 batches
	for range 5 {
		_, err := wp.Produce(ctx, fn, producer.ProduceOptions{})
		must(err)
	}
	assertIdempotencyKeysCount(ctx, ds, tp.Id, 5)

	// backdate them all past ttl
	_, err = ds.Pool.Exec(ctx, fmt.Sprintf(`UPDATE idempotency_key_%d SET created_at = now() - interval '1 hour';`, tp.Id))
	must(err)

	// one alive claim, published after the backdate, well inside ttl
	_, err = wp.Produce(ctx, fn, producer.ProduceOptions{})
	must(err)
	assertIdempotencyKeysCount(ctx, ds, tp.Id, 6)

	must(cd.SweepExpiredIdempotencyKeys(ctx, tp.Id, ttl, batchSize))

	assertIdempotencyKeysCount(ctx, ds, tp.Id, 1)
	fmt.Println("  ✓ 5 dormant claims swept across multiple batches, the 1 live claim survives")
}

func configRoundTripScenario(ctx context.Context, ds *coredatastore.PostgresDatastore) {
	step("config round trip: IdempotencyKeyTTL persists correctly through re-registration")

	topicName := fmt.Sprintf("phase9.idempotencykeyslab.roundtrip.%d", time.Now().UnixNano())
	defer func() { must(topic.Destroy(ctx, ds, topicName)) }()

	tp1, err := topic.Register(ctx, ds, topic.Config{Name: topicName, PartitionSize: 1000})
	must(err)
	if tp1.IdempotencyKeyTTL != time.Hour {
		die(fmt.Sprintf("default IdempotencyKeyTTL = %v, want 1h", tp1.IdempotencyKeyTTL))
	}

	// re-registering with the SAME (defaulted) config must NOT trip ErrTopicConfigMismatch --
	// this is the exact bug caught earlier: an unpersisted field compares as a mismatch
	// against itself on every re-register.
	_, err = topic.Register(ctx, ds, topic.Config{Name: topicName, PartitionSize: 1000})
	must(err)
	fmt.Println("  ✓ default IdempotencyKeyTTL (1h) survives a re-register with no mismatch")

	// a genuinely different IdempotencyKeyTTL on re-register must still be caught
	_, err = topic.Register(ctx, ds, topic.Config{Name: topicName, PartitionSize: 1000, IdempotencyKeyTTL: 2 * time.Hour})
	if err == nil {
		die("expected ErrTopicConfigMismatch for a changed IdempotencyKeyTTL, got nil")
	}
	fmt.Println("  ✓ a changed IdempotencyKeyTTL on re-register is correctly caught as a mismatch")
}

func skipIdempotencyScenario(ctx context.Context, ds *coredatastore.PostgresDatastore) {
	step("skip idempotency: opting out writes no claim row, and gives up retry-safety in exchange")

	topicName := fmt.Sprintf("phase9.idempotencykeyslab.skip.%d", time.Now().UnixNano())
	tp, err := topic.Register(ctx, ds, topic.Config{Name: topicName, PartitionSize: 1000})
	must(err)
	defer func() { must(topic.Destroy(ctx, ds, topicName)) }()

	pd := producer.NewProducerDatastore[common.Work](ds, nil)
	wp := producer.NewMessageProducer(tp, pd)

	key, err := uuid.NewV7()
	must(err)

	fn := func(ctx context.Context, tx producer.Tx, gotKey uuid.UUID) (*common.Work, error) {
		if gotKey != uuid.Nil {
			die("SkipIdempotency=true still resolved an idempotency key -- should stay uuid.Nil")
		}
		return common.NewWork(30, "admin@example.com")
	}

	// three "retries" under the same key, but SkipIdempotency=true -- no
	// claim gate, so this DOES double-publish. That's the tradeoff being
	// opted into, not a bug: the whole point is skipping the write that
	// would have prevented it.
	for range 3 {
		_, err := wp.Produce(ctx, fn, producer.ProduceOptions{IdempotencyKey: key, SkipIdempotency: true})
		must(err)
	}

	assertMessageLogCount(ctx, ds, tp.Id, 3)
	assertIdempotencyKeysCount(ctx, ds, tp.Id, 0)
	fmt.Println("  ✓ SkipIdempotency=true: IdempotencyKey ignored, zero claim rows written, and")
	fmt.Println("    (as expected) 3 calls under the same key produced 3 rows -- no protection, by design")

	// a protected call in the SAME topic right after is unaffected -- skip is per-call, not topic-wide
	protectedKey, err := uuid.NewV7()
	must(err)
	protectedFn := func(ctx context.Context, tx producer.Tx, gotKey uuid.UUID) (*common.Work, error) {
		if gotKey != protectedKey {
			die("a protected call in the same topic did not receive its own idempotency key")
		}
		return common.NewWork(30, "admin@example.com")
	}
	for range 3 {
		_, err := wp.Produce(ctx, protectedFn, producer.ProduceOptions{IdempotencyKey: protectedKey})
		must(err)
	}

	assertMessageLogCount(ctx, ds, tp.Id, 4) // 3 unprotected + 1 protected (deduped from 3 calls)
	assertIdempotencyKeysCount(ctx, ds, tp.Id, 1)
	fmt.Println("  ✓ a protected call right after in the same topic is unaffected -- opt-out is per-call, not topic-wide")
}

// ---- helpers ----

func assertMessageLogCount(ctx context.Context, ds *coredatastore.PostgresDatastore, topicID int64, want int) {
	var count int
	must(ds.Pool.QueryRow(ctx, fmt.Sprintf(`SELECT COUNT(*) FROM message_log_%d;`, topicID)).Scan(&count))
	if count != want {
		die(fmt.Sprintf("message_log_%d has %d rows, want %d", topicID, count, want))
	}
}

func assertIdempotencyKeysCount(ctx context.Context, ds *coredatastore.PostgresDatastore, topicID int64, want int) {
	var count int
	must(ds.Pool.QueryRow(ctx, fmt.Sprintf(`SELECT COUNT(*) FROM idempotency_key_%d;`, topicID)).Scan(&count))
	if count != want {
		die(fmt.Sprintf("idempotency_key_%d has %d rows, want %d", topicID, count, want))
	}
}

func step(s string) { fmt.Printf("\n--- %s ---\n", s) }
func must(err error) {
	if err != nil {
		die(err.Error())
	}
}
func die(msg string) {
	fmt.Printf("\n❌ LAB FAILED: %s\n", msg)
	os.Exit(1)
}
